{
    "name": "Production MME",
    "version": "16.0.1.0.0",
    "category": "Quality control",
    "license": "AGPL-3",
    "author": "TAMINA IGUIDER",
    "website": "maghrebmetal .com",
    "depends": ["base","quality_control_oca", "mrp", "product", "stock_no_negative", "margin_product_sale_invoice",
                "mrp_order_from_multiple_sale_order", "stock", "sale_management", "project","uom"],
    "data": [
        "data/quality_control_mrp_data.xml",
        "views/qc_inspection_view.xml",
        "views/mrp_production_view.xml",
        "views/product_jauge.xml",
        "views/product_template_view.xml",
        "views/sale_order_view.xml",
        "views/project_view.xml",
        "views/stock_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_company_views.xml",
        "reports/header_footer_mrp.xml",
        "reports/mrp.xml",
        "reports/header_footer_bareme.xml",
        "reports/bareme.xml",

    ],
    'application': True,
    "installable": True,
    "auto_install": True,
}
